### ISSUE TITLE
No feed

### ISSUE THREAD

**Issue by samueltardieu** [kyren/kyren.github.io#1]
Hi.

I wanted to add your blog to my newsreader, and unfortunately the feed referenced in `index.html` does not exist (https://kyren.github.io/feed.xml).

Could you consider generating it? It would ease following your blog in a timely fashion.

(see for example https://help.github.com/articles/atom-rss-feeds-for-github-pages/)

Thanks.

**Comment by kyren** [comment]
I think it's working now?

**Comment by samueltardieu** [comment]
Indeed. Thanks!
